[workspace]
members = ["crates/*"]
resolver = "2"

[workspace.package]
version = "0.1.0"
edition = "2021"
rust-version = "1.75"
authors = ["Christian Kemper <christian.kemper@kemper.buzz>"]
license = "MIT OR Apache-2.0"
repository = "https://github.com/ck3mp3r/bogita"
homepage = "https://github.com/ck3mp3r/bogita"

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
panic = "abort"
strip = true

[profile.release-with-debug]
inherits = "release"
strip = false
debug = true
